Update web_search.py
when we ask questions related to web search then it direct go to web search from router and as it only contain the questions (how to make pizza) so it give error of
 KeyError: 'documents' 
in
documents = state["documents"]

so for safety added the if condition